version: '3.8'
services:
  mongo_1:
    build: .
    image: mongo:6.0
    container_name: mongodb1
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=adminpassword